/*
 * generated by Xtext 2.10.0
 */
package es.uam.eps


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MedslStandaloneSetup extends MedslStandaloneSetupGenerated {

	def static void doSetup() {
		new MedslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
