/*
 * generated by Xtext 2.10.0
 */
package es.uam.eps.tests

import com.google.inject.Inject
import es.uam.eps.medsl.Domainmodel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MedslInjectorProvider)
class MedslParsingTest{

	@Inject
	ParseHelper<Domainmodel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
